### ISSUE TITLE
Upgrade Applicant Maps MongoDB to MongoDB v4.4

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-applicantmaps-api#20]
We need to upgrade our MongoDB cluster hosted as a Heroku addon for Applicant Maps to v4.4. ObjectRocket is the vendor that manages that cluster. They will perform the upgrades for us in designed maintenance windows, but we will need an engineer to work with them to execute manual tests after each upgrade. Engineers can test upgrades by confirmed that they can create and view new "projects" in Applicant Maps.

@TylerMatteo will loop in the assigned engineer once we have a date and time from ObjectRocket for the upgrades to be completed.

**Comment by horatiorosa** [comment]
Upgrade to `v4.4` completed
